export const FAKE_POPULARS = [
  {
    backdrop_path: "/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg",
    first_air_date: "2022-11-23",
    genre_ids: [10765, 9648, 35],
    id: 119051,
    name: "Wednesday",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Wednesday",
    overview:
      "Wednesday Addams is sent to Nevermore Academy, a bizarre boarding school where she attempts to master her psychic powers, stop a monstrous killing spree of the town citizens, and solve the supernatural mystery that affected her family 25 years ago — all while navigating her new relationships.",
    popularity: 2555.293,
    poster_path: "/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
    vote_average: 8.7,
    vote_count: 5391,
  },
];

//recommended tv shows list - 10

export const FAKE_RECOMMENDATIONS = [
  {
    adult: false,
    backdrop_path: "/s1xnjbOIQtwGObPnydTebp74G2c.jpg",
    id: 90669,
    name: "1899",
    original_language: "de",
    original_name: "1899",
    overview:
      "Passengers on an immigrant ship traveling to the new continent get caught in a mysterious riddle when they find a second vessel adrift on the open sea.",
    poster_path: "/gZleGu1MQVBArH2dlpZ9CGi0hhy.jpg",
    media_type: "tv",
    genre_ids: [9648, 18],
    popularity: 323.121,
    first_air_date: "2022-11-17",
    vote_average: 7.759,
    vote_count: 756,
    origin_country: ["DE"],
  },
  {
    adult: false,
    backdrop_path: "/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
    id: 66732,
    name: "Stranger Things",
    original_language: "en",
    original_name: "Stranger Things",
    overview:
      "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
    poster_path: "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    media_type: "tv",
    genre_ids: [18, 10765, 9648],
    popularity: 361.223,
    first_air_date: "2016-07-15",
    vote_average: 8.638,
    vote_count: 14896,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/EurcYIB7obJgoVzeui2RZkFlEm.jpg",
    id: 1396,
    name: "Breaking Bad",
    original_language: "en",
    original_name: "Breaking Bad",
    overview:
      "When Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
    poster_path: "/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 367.057,
    first_air_date: "2008-01-20",
    vote_average: 8.864,
    vote_count: 10911,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
    id: 94997,
    name: "House of the Dragon",
    original_language: "en",
    original_name: "House of the Dragon",
    overview:
      "The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires crumble from such heights. In the case of the Targaryens, their slow fall begins when King Viserys breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne. But when Viserys later fathers a son, the court is shocked when Rhaenyra retains her status as his heir, and seeds of division sow friction across the realm.",
    poster_path: "/1X4h40fcB4WWUmIBK0auT4zRBAV.jpg",
    media_type: "tv",
    genre_ids: [10765, 18, 10759],
    popularity: 462.769,
    first_air_date: "2022-08-21",
    vote_average: 8.488,
    vote_count: 2820,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/hIZFG7MK4leU4axRFKJWqrjhmxZ.jpg",
    id: 95403,
    name: "The Peripheral",
    original_language: "en",
    original_name: "The Peripheral",
    overview:
      "Stuck in a small Appalachian town, a young woman’s only escape from the daily grind is playing advanced video games. She is such a good player that a company sends her a new video game system to test…but it has a surprise in store. It unlocks all of her dreams of finding a purpose, romance, and glamour in what seems like a game…but it also puts her and her family in real danger.",
    poster_path: "/ccBe5BVeibdBEQU7l6P6BubajWV.jpg",
    media_type: "tv",
    genre_ids: [10765, 18],
    popularity: 326.903,
    first_air_date: "2022-10-20",
    vote_average: 8,
    vote_count: 530,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/bKxiLRPVWe2nZXCzt6JPr5HNWYm.jpg",
    id: 110316,
    name: "Alice in Borderland",
    original_language: "ja",
    original_name: "今際の国のアリス",
    overview:
      "With his two friends, a video-game-obsessed young man finds himself in a strange version of Tokyo where they must compete in dangerous games to win.",
    poster_path: "/uFXEoVPENgKJrkxFWlOhNMDwlEk.jpg",
    media_type: "tv",
    genre_ids: [18, 9648, 10759, 10765],
    popularity: 325.334,
    first_air_date: "2020-12-10",
    vote_average: 8.204,
    vote_count: 1255,
    origin_country: ["JP"],
  },
  {
    adult: false,
    backdrop_path: "/hoVuI69nygLQBJ4FqgRKnukDeKt.jpg",
    id: 106541,
    name: "The Witcher: Blood Origin",
    original_language: "en",
    original_name: "The Witcher: Blood Origin",
    overview:
      "More than a thousand years before the world of The Witcher, seven outcasts in the elven world unite in a blood quest against an unstoppable power.",
    poster_path: "/vpfJK9F0UJNcAIIeC42oJyKMnZQ.jpg",
    media_type: "tv",
    genre_ids: [10759, 10765],
    popularity: 667.135,
    first_air_date: "2022-12-25",
    vote_average: 6.962,
    vote_count: 343,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/93SxdkiR3gBcbG5FxIt0DCBttul.jpg",
    id: 111837,
    name: "Willow",
    original_language: "en",
    original_name: "Willow",
    overview:
      "Many years after the events of the original film, legendary sorcerer Willow leads a group of misfit heroes on a dangerous rescue mission through a world beyond their wildest imaginations.",
    poster_path: "/jhdSPDlhswjN1r6O0pGP3ZvQgU8.jpg",
    media_type: "tv",
    genre_ids: [10765, 10759, 18],
    popularity: 535.848,
    first_air_date: "2022-11-30",
    vote_average: 7.047,
    vote_count: 192,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/xYTnihl7qffiLSZ6yLMSpBkPdXC.jpg",
    id: 93405,
    name: "Squid Game",
    original_language: "ko",
    original_name: "오징어 게임",
    overview:
      "Hundreds of cash-strapped players accept a strange invitation to compete in children's games—with high stakes. But, a tempting prize awaits the victor.",
    poster_path: "/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg",
    media_type: "tv",
    genre_ids: [10759, 9648, 18],
    popularity: 186.53,
    first_air_date: "2021-09-17",
    vote_average: 7.8,
    vote_count: 12214,
    origin_country: ["KR"],
  },
  {
    adult: false,
    backdrop_path: "/5vUux2vNUTqwCzb7tVcH18XnsF.jpg",
    id: 113988,
    name: "Dahmer – Monster: The Jeffrey Dahmer Story",
    original_language: "en",
    original_name: "Dahmer – Monster: The Jeffrey Dahmer Story",
    overview:
      "This series examines the gruesome and horrific true crimes of Jeffrey Dahmer and the systemic failures that enabled one of America’s most notorious serial killers to continue his murderous spree in plain sight for over a decade.",
    poster_path: "/f2PVrphK0u81ES256lw3oAZuF3x.jpg",
    media_type: "tv",
    genre_ids: [80, 18],
    popularity: 275.762,
    first_air_date: "2022-09-21",
    vote_average: 8.13,
    vote_count: 1866,
    origin_country: ["US"],
  },
];
